// data.js (ES Module)

export const cafes = [
    {
        id: '1',
        name: '홍대 아트 카페',
        description: '예술과 커피가 만나는 감성 공간',
        location: '서울 마포구 홍익로 123',
        thumbnail: 'https://images.unsplash.com/photo-1739723745132-97df9db49db2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjb3p5JTIwY2FmZSUyMGludGVyaW9yfGVufDF8fHx8MTc4MTgyODYzNXww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
        menus: [
            {
                id: '1-1',
                name: '아메리카노',
                price: 4500,
                description: '깊고 진한 에스프레소의 풍미',
                category: '커피',
                image: 'https://images.unsplash.com/photo-1579992357154-faf4bde95b3d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxlc3ByZXNzbyUyMGNvZmZlZSUyMGN1cHxlbnwxfHx8fDE3ODE4Mjg2MzZ8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
            },
            {
                id: '1-2',
                name: '카페라떼',
                price: 5000,
                description: '부드러운 우유와 에스프레소의 조화',
                category: '커피',
                image: 'https://images.unsplash.com/photo-1507133750040-4a8f57021571',
            },
            {
                id: '1-3',
                name: '초코 케이크',
                price: 6500,
                description: '진한 초콜릿의 달콤함',
                category: '디저트',
                image: 'https://images.unsplash.com/photo-1583338917451-face2751d8d5',
            },
            {
                id: '1-4',
                name: '바닐라 라떼',
                price: 5500,
                description: '달콤한 바닐라 향이 가득한 라떼',
                category: '커피',
                image: 'https://images.unsplash.com/photo-1507133750040-4a8f57021571',
            },
        ],
    },

    {
        id: '2',
        name: '강남 모던 카페',
        description: '세련된 분위기의 프리미엄 카페',
        location: '서울 강남구 테헤란로 456',
        thumbnail: 'https://images.unsplash.com/photo-1464979681340-bdd28a61699e',
        menus: [
            {
                id: '2-1',
                name: '콜드브루',
                price: 5500,
                description: '12시간 저온 추출 콜드브루',
                category: '커피',
                image: 'https://images.unsplash.com/photo-1579992357154-faf4bde95b3d',
            },
            {
                id: '2-2',
                name: '카푸치노',
                price: 5000,
                description: '풍성한 우유 거품이 특징',
                category: '커피',
                image: 'https://images.unsplash.com/photo-1507133750040-4a8f57021571',
            },
            {
                id: '2-3',
                name: '티라미수',
                price: 7000,
                description: '이탈리안 정통 티라미수',
                category: '디저트',
                image: 'https://images.unsplash.com/photo-1583338917451-face2751d8d5',
            },
            {
                id: '2-4',
                name: '플랫화이트',
                price: 5500,
                description: '진한 에스프레소와 실키한 우유',
                category: '커피',
                image: 'https://images.unsplash.com/photo-1507133750040-4a8f57021571',
            },
        ],
    },

    {
        id: '3',
        name: '루프탑 카페',
        description: '하늘과 맞닿은 특별한 공간',
        location: '서울 용산구 이태원로 789',
        thumbnail: 'https://images.unsplash.com/photo-1621275471769-e6aa344546d5',
        menus: [
            {
                id: '3-1',
                name: '에스프레소',
                price: 4000,
                description: '강렬한 에스프레소 샷',
                category: '커피',
                image: 'https://images.unsplash.com/photo-1579992357154-faf4bde95b3d',
            },
            {
                id: '3-2',
                name: '카페모카',
                price: 5500,
                description: '초콜릿과 커피의 완벽한 조화',
                category: '커피',
                image: 'https://images.unsplash.com/photo-1507133750040-4a8f57021571',
            },
            {
                id: '3-3',
                name: '치즈케이크',
                price: 6500,
                description: '부드럽고 촉촉한 뉴욕 스타일',
                category: '디저트',
                image: 'https://images.unsplash.com/photo-1583338917451-face2751d8d5',
            },
            {
                id: '3-4',
                name: '아이스티',
                price: 4500,
                description: '상큼한 레몬 아이스티',
                category: '차',
                image: 'https://images.unsplash.com/photo-1579992357154-faf4bde95b3d',
            },
        ],
    },
];